Mount!!!!!!!

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

data_dir = '/content/gdrive/MyDrive/NLP Project/data/'

Mounted at /content/gdrive

Load test/train data

In [2]:
import numpy as np
# Ensure data_dir is set correctly
data_dir = '/content/gdrive/MyDrive/NLP Project/data/'

x_train_path = data_dir + "X_train_simplified.txt"
x_test_path = data_dir + "X_test_simplified.txt"
y_train_path = data_dir + "y_train_simplified.txt"
y_test_path = data_dir + "y_test_simplified.txt"

# Load X_train (sentences) as text
with open(x_train_path, 'r') as f:
    X_train = f.read().splitlines()

# Load X_test (sentences) as text
with open(x_test_path, 'r') as f:
    X_test = f.read().splitlines()

# Load y_train (labels) as text and convert to int
with open(y_train_path, 'r') as f:
    y_train = [line.strip() for line in f.read().splitlines()]

# Load y_test (labels) as text and convert to int
with open(y_test_path, 'r') as f:
    y_test = [line.strip() for line in f.read().splitlines()]

print(f"Loaded X_train samples: {len(X_train)}")
print(f"Loaded X_test samples: {len(X_test)}")
print(f"Loaded y_train samples: {len(y_train)}")
print(f"Loaded y_test samples: {len(y_test)}")

Loaded X_train samples: 15629
Loaded X_test samples: 3766
Loaded y_train samples: 15629
Loaded y_test samples: 3766

Create chart for the split data

In [3]:
import pandas as pd
from collections import Counter

categories = ['A', 'B', 'C']

# Map numerical categories from y_train/y_test to A, B, C
category_map = {'1': 'A', '2': 'B', '3': 'C'}

# Calculate counts for y_train
raw_train_counts = Counter(y_train)
train_counts = {category_map.get(k, k): v for k, v in raw_train_counts.items()}
train_stats = {cat: train_counts.get(cat, 0) for cat in categories}
train_stats['Total'] = len(y_train)

# Calculate counts for y_test
raw_test_counts = Counter(y_test)
test_counts = {category_map.get(k, k): v for k, v in raw_test_counts.items()}
test_stats = {cat: test_counts.get(cat, 0) for cat in categories}
test_stats['Total'] = len(y_test)

# Hardcoded GITHUB and KAGGLE stats as provided by setup data
github_stats = {'A': 3131, 'B': 6238, 'C': 675, 'Total': 10044}
kaggle_stats = {'A': 4176, 'B': 0, 'C': 1602, 'Total': 5778}

# Create a dictionary to hold all data for the DataFrame with the desired order
data = {
    'Source': ['GITHUB', 'KAGGLE', 'TOTAL', 'TEST', 'TRAIN']
}

# Initialize category and total columns with placeholders
for cat in categories:
    data[cat] = [0] * len(data['Source'])
data['Total'] = [0] * len(data['Source'])

# Populate data for GITHUB
data['A'][0] = github_stats['A']
data['B'][0] = github_stats['B']
data['C'][0] = github_stats['C']
data['Total'][0] = github_stats['Total']

# Populate data for KAGGLE
data['A'][1] = kaggle_stats['A']
data['B'][1] = kaggle_stats['B']
data['C'][1] = kaggle_stats['C']
data['Total'][1] = kaggle_stats['Total']

# Populate data for TEST
data['A'][3] = test_stats['A']
data['B'][3] = test_stats['B']
data['C'][3] = test_stats['C']
data['Total'][3] = test_stats['Total']

# Populate data for TRAIN
data['A'][4] = train_stats['A']
data['B'][4] = train_stats['B']
data['C'][4] = train_stats['C']
data['Total'][4] = train_stats['Total']

# Calculate and populate data for the overall TOTAL row (sum of all distinct sources)
for cat in categories:
    data[cat][2] = data[cat][0] + data[cat][1] + data[cat][3] + data[cat][4] # GITHUB + KAGGLE + TEST + TRAIN
data['Total'][2] = data['Total'][0] + data['Total'][1] + data['Total'][3] + data['Total'][4] # Sum of all totals

# Create DataFrame
df_stats = pd.DataFrame(data)

# Function to apply styling for borders
def apply_border_style(row):
    styles = [''] * len(row)
    if row['Source'] == 'KAGGLE':
        # Add a thicker bottom border after KAGGLE
        styles = ['border-bottom: 2px solid black'] * len(row)
    elif row['Source'] == 'TOTAL':
        # Add a thicker bottom border after TOTAL
        styles = ['border-bottom: 2px solid black'] * len(row)
    return styles

# Apply the styling to the DataFrame and display
display(df_stats.style.apply(apply_border_style, axis=1))

In [4]:
import numpy as np
# Ensure data_dir is set correctly
data_dir = '/content/gdrive/MyDrive/NLP Project/data/'

x_train_path = data_dir + "X_train.txt"
x_test_path = data_dir + "X_test.txt"
y_train_path = data_dir + "y_train.txt"
y_test_path = data_dir + "y_test.txt"

# Load X_train (sentences) as text
with open(x_train_path, 'r') as f:
    X_train = f.read().splitlines()

# Load X_test (sentences) as text
with open(x_test_path, 'r') as f:
    X_test = f.read().splitlines()

# Load y_train (labels) as text and convert to int
with open(y_train_path, 'r') as f:
    y_train = [line.strip() for line in f.read().splitlines()]

# Load y_test (labels) as text and convert to int
with open(y_test_path, 'r') as f:
    y_test = [line.strip() for line in f.read().splitlines()]

print(f"Loaded X_train samples: {len(X_train)}")
print(f"Loaded X_test samples: {len(X_test)}")
print(f"Loaded y_train samples: {len(y_train)}")
print(f"Loaded y_test samples: {len(y_test)}")

Loaded X_train samples: 15629
Loaded X_test samples: 3766
Loaded y_train samples: 15629
Loaded y_test samples: 3766

In [5]:
import pandas as pd
from collections import Counter

levels = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']

train_counts = Counter(y_train)
test_counts = Counter(y_test)

train_stats = {lvl: train_counts.get(lvl, 0) for lvl in levels}
train_stats['Total'] = len(y_train)

test_stats = {lvl: test_counts.get(lvl, 0) for lvl in levels}
test_stats['Total'] = len(y_test)

github_stats = {'A1': 704, 'A2': 2427, 'B1': 3704, 'B2': 2534, 'C1': 638, 'C2': 37, 'Total': 10044}
kaggle_stats = {'A1': 4176, 'A2': 0, 'B1': 0, 'B2': 0, 'C1': 0, 'C2': 1213, 'Total': 5389}
total_stats = {'A1': 4803, 'A2': 2427, 'B1': 3703, 'B2': 2534, 'C1': 638, 'C2': 1250, 'Total': 15355}

df_stats = pd.DataFrame({
    'Source': ['GITHUB', 'KAGGLE', 'TOTAL', 'TRAIN', 'TEST'],
    'A1': [github_stats['A1'], kaggle_stats['A1'], total_stats['A1'], train_stats['A1'], test_stats['A1']],
    'A2': [github_stats['A2'], kaggle_stats['A2'], total_stats['A2'], train_stats['A2'], test_stats['A2']],
    'B1': [github_stats['B1'], kaggle_stats['B1'], total_stats['B1'], train_stats['B1'], test_stats['B1']],
    'B2': [github_stats['B2'], kaggle_stats['B2'], total_stats['B2'], train_stats['B2'], test_stats['B2']],
    'C1': [github_stats['C1'], kaggle_stats['C1'], total_stats['C1'], train_stats['C1'], test_stats['C1']],
    'C2': [github_stats['C2'], kaggle_stats['C2'], total_stats['C2'], train_stats['C2'], test_stats['C2']],
    'Total': [
        github_stats['Total'],
        kaggle_stats['Total'],
        total_stats['Total'],
        train_stats['Total'],
        test_stats['Total']
    ]
})

display(df_stats.style.apply(apply_border_style, axis=1))